version: '3.1'

services:
  php:
    build:
      context: ./Docker
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - .:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 9191:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: secret

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      # MYSQL_USERNAME: root
      # MYSQL_ROOT_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - ./storage/db:/var/lib/mysql
      #- ./storage/db/mysql
      #- .:/var/www/html/./storage/db/mysql
      #- ./storage/db:/mysql



